# ~/.config/hypr/hyprpaper.conf

# IPC 기능을 쓰지 않을 거면 off, 쓸 거면 on
ipc = off

# Hyprland 시작 시 미리 로드할 이미지
# preload = ~/.config/hypr/thinkpad_wallpaper.png
preload = ~/.config/hypr/login_wallpaper.png

# 모든 모니터(*), 단일 이미지 지정
# wallpaper = , ~/.config/hypr/thinkpad_wallpaper.png
wallpaper = , ~/.config/hypr/login_wallpaper.png

# 이미지 표시 방식: fill, fit, center, stretch, tile 중 선택
mode = fill
