# ~/.config/hypr/hyprpaper.conf

# IPC 안 쓸 거면 false, 쓸 거면 true
ipc = false

# 모든 모니터에 같은 배경 사용
wallpaper {
    monitor =
    path = ~/.config/hypr/PSG_wallpaper.png
    # 이미지 표시 방식: fill, fit, center, stretch, tile 중 선택
    # fit_mode = fill
    fit_mode = fit
}

